require("core.plugin_config.colorscheme")
--require("core.plugin_config.gruvbox") -- uncomment this line if you want to use gruvbox
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.vim-test")
require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.gitsigns")
require("core.plugin_config.copilot")
require("core.plugin_config.mason-config")
require("core.plugin_config.feline_config")
